#rootUrl: http://varya.me
rootUrl: http://localhost:9778/
gridUrl: http://localhost:4444/wd/hub

browsers:
  chrome:
    browserName: chrome
    version: "37.0"

  firefox:
    browserName: firefox
    version: "31.0"

windowSize: 1600x1200
